version: '3'
services: 
  intel: 
    restart: always
    container_name: intel
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 9193:9193
    environment:
      - VIRTUAL_HOST=intelligence.shuttlers.africa
      - LETSENCRYPT_HOST=intelligence.shuttlers.africa
      - MONGO_URI=mongodb://mongodb:27017
      - CONN_STR=mongodb://mongodb:27017
    command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
    volumes:
      - .:/src
      - .:/var/www
    links:
      - mongodb
    depends_on:
      - mongodb
  
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      - VIRTUAL_HOST=mongodb://mongodb:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '127.0.0.1:8089:8089'
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      VIRTUAL_HOST: mongo-express.shuttlers.africa